# Generated by Django 5.0.1 on 2024-01-11 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookmaker", "0002_remove_bet_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="bet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bookmaker.bet",
            ),
        ),
    ]
