# Generated by Django 5.0.1 on 2024-01-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookmaker", "0002_alter_bet_draw_money_wagered_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bet",
            name="draw_money_wagered",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="bet",
            name="loose_money_wagered",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="bet",
            name="win_money_wagered",
            field=models.IntegerField(default=0),
        ),
    ]
