# Generated by Django 5.0.1 on 2024-01-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookmaker", "0002_remove_bet_draw_money_wagered_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bet",
            name="resolved",
            field=models.BooleanField(default=False),
        ),
    ]
