# Generated by Django 5.0.1 on 2024-01-11 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookmaker", "0003_comment_bet"),
    ]

    operations = [
        migrations.AddField(
            model_name="bet",
            name="possible_to_draw",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="comment",
            name="bet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="bookmaker.bet",
            ),
        ),
    ]
